comidas = ['leite', 'couve','computador', 'tomate','garfo','faca','tablet','refrigerante']
bebidas = ['uva', 'colher','TV','vinho','cerveja','celular','banana']
talheres = ['arroz','iPhone', 'concha','whisky','vodka','feijão','colher de chá']
eletronicos=[]
comidas.pop(0)
comidas.pop(1)
comidas.pop(2)
comidas.pop(2)
comidas.pop(2)
comidas.pop(2)
bebidas.append("leite")
bebidas.append("refrigerante")
talheres.append("garfo")
talheres.append("faca")
eletronicos.append("computador")
eletronicos.append("tablet")
bebidas.pop(0)
bebidas.pop(0)
bebidas.pop(0)
bebidas.pop(2)
bebidas.pop(2)
comidas.append("uva")
comidas.append("banana")
talheres.append("colher")
eletronicos.append("TV")
eletronicos.append("celular")
talheres.pop(0)
talheres.pop(0)
talheres.pop(1)
talheres.pop(1)
talheres.pop(1)
comidas.append("arroz")
comidas.append("feijão")
bebidas.append("whisky")
bebidas.append("vodka")
eletronicos.append("iphone")
print ("comidas: ", comidas)
print ("bebidas: ", bebidas)
print ("talheres: ", talheres)
print ("eletronicos: ", eletronicos)